use [bank loan]
Select * from [bank_loan_data ]

                      --1ST SUMMARY--
               
--1) TOTAL LOAN APPLICATIONS (38576)
SELECT COUNT(ID) AS [TOTAL LOAN APPLICATION]  FROM [bank_loan_data ]

--2)TOTAL MTD APPLICATIONS (4314)
SELECT COUNT(ID) AS [MTD TOTAL LOAN APPLICATION]  FROM [bank_loan_data ]
WHERE MONTH(ISSUE_DATE)=12 AND YEAR(ISSUE_DATE)=2021

--3)TOTAL PMTD APPLICATIONS (4035)
SELECT COUNT(ID) AS [PMTD TOTAL LOAN APPLICATION]  FROM [bank_loan_data ]
WHERE MONTH(ISSUE_DATE)=11 AND YEAR(ISSUE_DATE)=2021

--4) TOTAL FUNDED AMOUNT (435757075)
SELECT SUM(LOAN_AMOUNT) AS [TOTAL FUNDED AMOUNT]  FROM [bank_loan_data ]

--5)MONTH TOTAL FUNDED AMOUNT (53981425)
SELECT SUM(LOAN_AMOUNT) AS [MONTH TOTAL FUNDED AMOUNT]  FROM [bank_loan_data ]
WHERE MONTH(ISSUE_DATE)=12 AND YEAR(ISSUE_DATE)=2021

--6)PREVIOUS MONTH TOTAL FUNDED AMOUNT (53981425)
SELECT SUM(LOAN_AMOUNT) AS [PREVIOUS MONTH TOTAL FUNDED AMOUNT]  FROM [bank_loan_data ]
WHERE MONTH(ISSUE_DATE)=11 AND YEAR(ISSUE_DATE)=2021

--7)TOTAL PAYMENTT RECIEVED  (58074380 and 50132030)
SELECT SUM(TOTAL_PAYMENT) AS [MONTH TOTAL AMOUNT RECIEVED] FROM BANK_LOAN_DATA
WHERE MONTH(ISSUE_DATE)=12 AND YEAR(ISSUE_DATE)=2021

SELECT SUM(TOTAL_PAYMENT) AS [PREVIOUS MONTH TOTAL AMOUNT RECIEVED] FROM BANK_LOAN_DATA
WHERE MONTH(ISSUE_DATE)=11 AND YEAR(ISSUE_DATE)=2021

--8)AVERAGE RATE OF INTEREST (12.36,11.94)
SELECT ROUND(AVG(INT_RATE)*100,2) AS [AVERAGE RATE] FROM [bank_loan_data]
WHERE MONTH(ISSUE_DATE)=12 AND YEAR(ISSUE_DATE)=2021

SELECT ROUND(AVG(INT_RATE)*100,2) AS [PREVIOUS AVERAGE RATE] FROM [bank_loan_data]
WHERE MONTH(ISSUE_DATE)=11 AND YEAR(ISSUE_DATE)=2021

--9) AVERAGE DTI (13.67 AND 13.3)

SELECT ROUND(AVG(DTI)*100,2) FROM [bank_loan_data ]
WHERE MONTH(ISSUE_DATE)=12 AND YEAR(ISSUE_DATE)=2021

SELECT ROUND(AVG(DTI)*100,2) FROM [bank_loan_data ]
WHERE MONTH(ISSUE_DATE)=11 AND YEAR(ISSUE_DATE)=2021

                            --2ND SUMMARY--

--1) GOOD LOAN AND BAD LOAN PERCENTAGE (86 ,13)

SELECT
(COUNT(CASE WHEN LOAN_STATUS = 'Fully Paid'OR LOAN_STATUS= 'Current' THEN id END )*100)/COUNT(ID) AS [GOOD LOAN %]
FROM [bank_loan_data ]

SELECT
(COUNT(CASE WHEN LOAN_STATUS = 'Charged Off ' THEN id END )*100)/COUNT(ID) AS [BAD LOAN %]
FROM [bank_loan_data ]

--2) TOTAL GOOD and BAD LOAN APPLICATIONS (33243,5333)
SELECT COUNT(ID) AS [GOOD LOAN APPLICATIONS] FROM [bank_loan_data ]
WHERE LOAN_STATUS = 'Fully Paid'OR LOAN_STATUS= 'Current' 

SELECT COUNT(ID) AS [GOOD LOAN APPLICATIONS] FROM [bank_loan_data ]
WHERE LOAN_STATUS = 'Charged Off'

--3)FUNDED AMOUNT IN GOOD and BAD LOAN APPLIACTIONS (370224850,65532225)
SELECT SUM(LOAN_AMOUNT) AS [FUNDED IN GOOD LOAN] FROM [bank_loan_data ]
WHERE LOAN_STATUS = 'Fully Paid'OR LOAN_STATUS= 'Current' 

SELECT SUM(LOAN_AMOUNT) AS [FUNDED IN GOOD LOAN] FROM [bank_loan_data ]
WHERE LOAN_STATUS = 'Charged Off'

--4)RECIEVED AMOUNT IN GOOD LOAN APPLIACTIONS (435786170,37284763)
SELECT SUM(total_payment) AS [FUNDED IN GOOD LOAN] FROM [bank_loan_data ]
WHERE LOAN_STATUS = 'Fully Paid'OR LOAN_STATUS= 'Current'

SELECT SUM(total_payment) AS [FUNDED IN GOOD LOAN] FROM [bank_loan_data ]
WHERE LOAN_STATUS = 'Charged Off'


   
                    --------3RD SUMMARY--------------
--1)AMOUNT ANALYSIS 
SELECT 
COUNT(ID) AS [TOTAL APPLICATIONS],
SUM(TOTAL_PAYMENT) AS [TOTAL PAYMENT RECIEVED],
SUM(LOAN_AMOUNT) AS [TOTAL FUNDED AMOUNT],
ROUND(AVG(INT_RATE)*100,2) AS [AVG INTEREST RATE],
ROUND(AVG(DTI)*100,2) AS DTI
FROM [bank_loan_data ]
GROUP BY loan_status

--2)CURRENT AND PREVIOUS MONTH AMOUNT ANALYSIS
/*Fully Paid	3321	42420451	37375675	11.39	13.07
Charged Off	561	3994065	7511175	14.31	14.13
Current	153	3717514	2867975	15.22	15.36


Fully Paid	3321	42420451	37375675	11.39	13.07
Charged Off	561	3994065	7511175	14.31	14.13
Current	153	3717514	2867975	15.22	15.36*/


SELECT 
LOAN_STATUS,
COUNT(ID) AS [TOTAL APPLICATIONS],
SUM(TOTAL_PAYMENT) AS [TOTAL PAYMENT RECIEVED],
SUM(LOAN_AMOUNT) AS [TOTAL FUNDED AMOUNT],
ROUND(AVG(INT_RATE)*100,2) AS [AVG INTEREST RATE],
ROUND(AVG(DTI)*100,2) AS DTI
FROM [bank_loan_data ]
WHERE MONTH(ISSUE_DATE)=12 
GROUP BY loan_status


SELECT 
LOAN_STATUS,
COUNT(ID) AS [TOTAL APPLICATIONS],
SUM(TOTAL_PAYMENT) AS [TOTAL PAYMENT RECIEVED],
SUM(LOAN_AMOUNT) AS [TOTAL FUNDED AMOUNT],
ROUND(AVG(INT_RATE)*100,2) AS [AVG INTEREST RATE],
ROUND(AVG(DTI)*100,2) AS DTI
FROM [bank_loan_data ]
WHERE MONTH(ISSUE_DATE)=11
GROUP BY loan_status



--------------------------------------------------
--1)
SELECT
MONTH(ISSUE_DATE) AS [MONTH NO],
DATENAME(MONTH,ISSUE_DATE) AS [MONTH],
COUNT(ID) AS [TOTAL APPLICATION],
SUM(LOAN_AMOUNT) AS [TOTAL FUNDED],
SUM(TOTAL_PAYMENT) AS [RECIEVED AMOUNT]
FROM [bank_loan_data ]
GROUP BY MONTH(ISSUE_DATE),DATENAME(MONTH,ISSUE_DATE)
ORDER BY MONTH(ISSUE_DATE)

--2)
SELECT
ADDRESS_STATE,
COUNT(ID) AS [TOTAL APPLICATION],
SUM(LOAN_AMOUNT) AS [TOTAL FUNDED],
SUM(TOTAL_PAYMENT) AS [RECIEVED AMOUNT]
FROM [bank_loan_data ]
GROUP BY ADDRESS_STATE
ORDER BY ADDRESS_STATE DESC

--3)
SELECT
TERM,
COUNT(ID) AS [TOTAL APPLICATION],
SUM(LOAN_AMOUNT) AS [TOTAL FUNDED],
SUM(TOTAL_PAYMENT) AS [RECIEVED AMOUNT]
FROM [bank_loan_data ]
GROUP BY TERM
ORDER BY TERM DESC


--4)
SELECT
EMP_LENGTH,
COUNT(ID) AS [TOTAL APPLICATION],
SUM(LOAN_AMOUNT) AS [TOTAL FUNDED],
SUM(TOTAL_PAYMENT) AS [RECIEVED AMOUNT]
FROM [bank_loan_data ]
GROUP BY EMP_LENGTH
ORDER BY COUNT(ID) DESC

--5)

SELECT 
PURPOSE,
COUNT(ID) AS [TOTAL APPLICATION],
SUM(LOAN_AMOUNT) AS [TOTAL FUNDED],
SUM(TOTAL_PAYMENT) AS [RECIEVED AMOUNT]
FROM [bank_loan_data ]
GROUP BY purpose


--6)
SELECT
HOME_OWNERSHIP,
COUNT(ID) AS [TOTAL APPLICATION],
SUM(LOAN_AMOUNT) AS [TOTAL FUNDED],
SUM(TOTAL_PAYMENT) AS [RECIEVED AMOUNT]
FROM [bank_loan_data ]
GROUP BY HOME_OWNERSHIP

SELECT
HOME_OWNERSHIP,
COUNT(ID) AS [TOTAL APPLICATION],
SUM(LOAN_AMOUNT) AS [TOTAL FUNDED],
SUM(TOTAL_PAYMENT) AS [RECIEVED AMOUNT]
FROM [bank_loan_data ]
WHERE GRADE='A'
GROUP BY HOME_OWNERSHIP